runtime: python39
entrypoint: gunicorn -b :$PORT app:app

instance_class: F2

env_variables:
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://aarya:aarya123@/book?unix_socket=/cloudsql/online-bookstore-428523:us-central1:bookstore"
  JWT_SECRET_KEY: "your_jwt_secret_key"

beta_settings:
  cloud_sql_instances: "online-bookstore-428523:us-central1:bookstore"


